# VacationPy

In [1]:
# Imports and keys
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import gmaps

In [7]:
# Import API key
from llavero import gkey

# Create a heat map that displays the humidity for every city from Part I.

In [14]:
# Import Data from las excercise
old_data = "../WeatherPy/weather_df.csv"
cities = pd.read_csv(old_data)
city_data = cities[cities["Cloudiness"] > 0]
city_data

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lon,Hi Temp,Wind Speed
0,0,Sisophon,91.0,KH,1.619745e+09,78.0,13.5859,102.9737,26.92,2.67
1,1,San Cristobal,75.0,VE,1.619745e+09,100.0,7.7669,-72.2250,24.00,1.54
2,2,Cam Ranh,20.0,VN,1.619745e+09,65.0,11.9214,109.1591,29.00,2.06
4,4,Yellowknife,75.0,CA,1.619744e+09,59.0,62.4560,-114.3525,-1.11,6.17
5,5,Lebu,100.0,CL,1.619744e+09,94.0,-37.6167,-73.6500,12.83,3.42
...,...,...,...,...,...,...,...,...,...,...
1395,1395,Rikitea,77.0,PF,1.619744e+09,66.0,-23.1203,-134.9692,24.79,5.37
1396,1396,Sobolevo,100.0,RU,1.619745e+09,86.0,54.4299,31.8996,7.55,5.53
1397,1397,Albany,100.0,US,1.619744e+09,90.0,42.6001,-73.9662,12.78,0.45
1398,1398,San Ciro De Acosta,57.0,MX,1.619745e+09,69.0,21.6333,-99.8167,26.80,8.71
1399,1399,Petropavlovsk-Kamchatskiy,20.0,RU,1.619745e+09,61.0,53.0452,158.6483,9.00,3.00

In [16]:
# Create a Humidity Heatmap Layer
hum_hm = city_data["Humidity"].astype(float)
loc_hm.head()

       Lat       Lon
0  13.5859  102.9737
1   7.7669  -72.2250
2  11.9214  109.1591
4  62.4560 -114.3525
5 -37.6167  -73.6500

In [17]:
# Create a Humidity Heatmap Layer
hum_hm = city_data["Humidity"].astype(float)
hum_hm.head()

0     78.0
1    100.0
2     65.0
4     59.0
5     94.0
Name: Humidity, dtype: float64

In [18]:
fig = gmaps.figure()
humidity_hm = gmaps.heatmap_layer(loc_hm, weights=hum_hm,
                                        dissipating=False, max_intensity=10,
                                        point_radius=3)
fig.add_layer(humidity_hm)
fig

Figure(layout=FigureLayout(height='420px'))