# VacationPy

In [10]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Otras
%matplotlib inline

In [11]:
# Import API key
from llavero import gkey

# Create a heat map that displays the humidity for every city from Part I.

In [12]:
# Import Data from las excercise
old_data = "../WeatherPy/weather_df.csv"
cities = pd.read_csv(old_data)
city_data = cities[cities["Cloudiness"] > 0]     # Eliminate rows without data
city_data

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lon,Hi Temp,Wind Speed
0,0,Sisophon,91.0,KH,1.619745e+09,78.0,13.5859,102.9737,26.92,2.67
1,1,San Cristobal,75.0,VE,1.619745e+09,100.0,7.7669,-72.2250,24.00,1.54
2,2,Cam Ranh,20.0,VN,1.619745e+09,65.0,11.9214,109.1591,29.00,2.06
4,4,Yellowknife,75.0,CA,1.619744e+09,59.0,62.4560,-114.3525,-1.11,6.17
5,5,Lebu,100.0,CL,1.619744e+09,94.0,-37.6167,-73.6500,12.83,3.42
...,...,...,...,...,...,...,...,...,...,...
1395,1395,Rikitea,77.0,PF,1.619744e+09,66.0,-23.1203,-134.9692,24.79,5.37
1396,1396,Sobolevo,100.0,RU,1.619745e+09,86.0,54.4299,31.8996,7.55,5.53
1397,1397,Albany,100.0,US,1.619744e+09,90.0,42.6001,-73.9662,12.78,0.45
1398,1398,San Ciro De Acosta,57.0,MX,1.619745e+09,69.0,21.6333,-99.8167,26.80,8.71
1399,1399,Petropavlovsk-Kamchatskiy,20.0,RU,1.619745e+09,61.0,53.0452,158.6483,9.00,3.00

In [13]:
# Create a Humidity Heatmap Layer
loc_hm = city_data[['Lat','Lon']].astype(float)
loc_hm.head()

       Lat       Lon
0  13.5859  102.9737
1   7.7669  -72.2250
2  11.9214  109.1591
4  62.4560 -114.3525
5 -37.6167  -73.6500

In [14]:
# Create a Humidity Heatmap Layer
hum_hm = city_data["Humidity"].astype(float)
hum_df = pd.DataFrame(hum_hm)
hum_df.head()

   Humidity
0      78.0
1     100.0
2      65.0
4      59.0
5      94.0

In [18]:
# Plot Heatmap
figure_layout = {
    'width': '1000px',
    'height': '800px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}


fig = gmaps.figure(layout=figure_layout, zoom_level=2, center=((28,2)))

 
heat_layer = gmaps.heatmap_layer(loc_hm, weights=hum_hm, 
                                 dissipating=False, max_intensity=100, point_radius=3)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='800px', margin='0 auto 0 auto', padding='1px', wiâ€¦

In [ ]:
# Select criteria to map
# A max temperature lower than 25 degrees Celsius but higher than 18 degrees Celsius.
# Wind speed less than 10 km/h.
# Zero cloudiness.
mycities = city_data
mycities = mycities[mycities['Hi Temp'] <= 25]
mycities = mycities[mycities['Hi Temp'] > 18]
mycities = mycities[mycities['Wind Speed'] <= 16]
mycities = mycities[mycities['Cloudiness'] <= 25]
mycities.head()

* Using Google Places API to find the first hotel for each city located within 5000 meters of your coordinates.
* Plot the hotels on top of the humidity heatmap with each pin containing the Hotel Name, City, and Country.

Hotel Map

* Store into variable named hotel_df.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
hotel_df = mycities
hotel_df["Hotel"] = ""
hotel_df

In [ ]:
# Look for nearby hotels in the selected regions
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
hotel_per_city = hotel_df[['City','Lat','Lon']]
hotel = []
for index, row in hotel_per_city.iterrows():
    lats = hotel_per_city['Lat'][index]
    lngs = hotel_per_city['Lon'][index]
    params = {
        "location": f"{lats},{lngs}",  
        "rankby": "distance",
        "keyword": "hotel",
        "key": gkey,}
    response = requests.get(base_url, params=params).json()
    try:
        results = response['results']
        hotel.append(results[0]['name'])
    except:
        hotel_df = hotel_df.drop(index)
hotel

In [ ]:
# Integrate hotel list to column in dataframe
hotel_df = pd.DataFrame(hotel_df)
hotel_df['Hotel Name'] = hotel
hotel_df

In [20]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[['Lat', 'Lon']]

NameError: name 'hotel_df' is not defined

In [19]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

NameError: name 'locations' is not defined